
logging:
  # The minimum logging level for console messages
  # (via Winston, https://github.com/flatiron/winston)
  level: debug

# Gonzales server settings.
proxy:
  # Gonzales listen port.
  port: 55055
  # SSL key path.
  sslKeyPath: ./keys/key.pem
  # SSL certificate path.
  sslCertPath: ./keys/crt.pem

  # Whether or not the proxy will follow redirects
  # itself or pass them back to the client
  followRedirects: false

# PAC (proxy auto config) server settings.
pac:
  # PAC server listen port.
  port: 55155

# Plugin settings below

# Cache settings.
cache:
  # Enable cache. Don't rename it to 'enabled' as this will crash the parser.
  enabled: true
  # Supported cache types are:
  # - basic (in-memory JS)
  # - redis (requires Redis database)
  type: basic
  # Settings for non-basic database server.
  database:
    host: localhost
    port: 55255
  # Expiration time settings for cache items in seconds.
  expire:
    default: 30
    max: 604800
  # Cache items management.
  items:
    enabled: false
    limit: 5000000
  # Cache memory usage settings in MB.
  memory:
    enabled: true
    limit: 2000

imgcompression:
  enabled: true

adblock:
  enabled: false

gzip:
  # Compression level for gzip.
  level: 9

# Block gif2video by default
gif2video:
  enabled: false
